### ISSUE TITLE
derive(SizeWith) should use SizeWith recursively, not mem::size_of

### ISSUE THREAD

**Issue by luser** [m4b/scroll_derive#12]
Currently [the `derive(SizeWith)` implementation](https://github.com/m4b/scroll_derive/blob/f41ecd49b76d835c48e3e0c0f0b44e7e1a391d50/src/lib.rs#L148) uses `mem::size_of` for individual fields. Unfortunately this means that it won't produce the correct results unless you use `#[repr(C, packed)]` on all your structs, which is a real pain to use nowadays because of the "can't safely take a reference to a packed struct field" warnings.

It would be nicer if it instead returned the sum of calling `size_with` for each field in the struct so that it would work correctly without `packed`.

**Comment by m4b** [comment]
Hmmm, I’m not sure I understand exactly how this would be fixed. I agree should avoid requiring users to use packed but I thought that size_with just used sizeof on the whole type, which means it shouldn’t require packed ?

**Comment by luser** [comment]
The problem is that `mem::size_of` includes padding and alignment, so if you have like:
```rust
struct A { a: u32, b: u64 }
struct B { a: A }
```

Then `mem::size_of::<A>()` is going to wind up being 16 bytes on most platforms due to alignment, so the `SizeWith` implementation of `B` will wind up reporting 16 bytes.

I cooked up a patch that just returns the sum of `ty::size_with(ctx)` for every member in a struct and it seems to work fine, and rustc is smart enough to constant-fold the whole thing down to a single constant.

**Comment by m4b** [comment]
Hmmm that makes me a little nervous. All of goblin relies now on size_with impls for writing, but iiuc, doesn’t removing the size_of calls commit us to a packed serialization of all structs ? Maybe I’m missing something.

But I’m very wary of changing important SizeWith details at this time because of the obscure bugs it might cause downstream ? That’s my major concern, but again perhaps I’m missing something ?

**Comment by luser** [comment]
> Hmmm that makes me a little nervous. All of goblin relies now on size_with impls for writing, but iiuc, doesn’t removing the size_of calls commit us to a packed serialization of all structs ? Maybe I’m missing something.

It does, but I'm not sure what the alternative is. Without `#[repr(C)]`, the actual memory layout of Rust structs is implementation-defined anyway. `scroll` currently just serializes and deserializes struct fields in the order they're declared without any padding or alignment, which seems like the thing everyone would want. If you need padding or alignment in a struct it's straightforward to add extra fields to get that, but it's pretty hard to go the other day.

Do you have a concrete use case in mind for non-packed serialization?

**Comment by m4b** [comment]
Ok, I think you're right.

Specifically, I don't have anything really in mind for non-packed serialization, _except_ all of the structs in goblin, which are `[repr(C)]`; however, afaics, they were all designed to include padding and alignment issues (like you suggest above), so that they're essentially "packed" structs on disk/in binaries.

So to clarify, will your changes will only require users to do `[repr(C)]` and not packed? And will this will be backwards compatible for anyone relying on the "older" version of scroll? Specifically, I worry about the structs in goblin (which are all `repr(C)` i believe).

It's ok if some or all of these are no, I'm just trying to assess the damage level if we go your route; if we do break stuff, i'm 50% ok with it as a "one last breakage before 1.0 thing", **as long as** there's a compelling reason, and we won't go back/revert, and its just the right/intuitive/most safe/friendly/future thinking path, etc.

Haha, ok that was a lot of requirements, but to be clear this sounds good to me I think, just being somewhat wary about essentially what could be a breaking a ABI change to anyone using this (which includes me).

Lastly, I've been trying to avoid scroll as a "serialization" library, and was originally designed just for numbers and simple Pods, but I guess its unrealistic, since it can really read or write pretty much anything, and I was just fooling myself; so I guess its better to settle on a  specific data layout it requires for reading and writing? (and in case it wasn't clear, it _always_ has to be able to read and write structs inside of binaries, which is its raison d'être)

Anyway, @luser, thanks for your valuable suggestions here and elsewhere, always appreciated :)

**Comment by luser** [comment]
> So to clarify, will your changes will only require users to do [repr(C)] and not packed? And will this will be backwards compatible for anyone relying on the "older" version of scroll? Specifically, I worry about the structs in goblin (which are all repr(C) i believe).

I don't think it'll require any `repr` at all--the way scroll works doesn't rely on the exact memory layout of structs, right? The `SizeWith` trait is simply to allow reading the right number of bytes from a `Read` impl.

As it stands, I decided to work around this issue by changing my minidump crate to use `memmap` instead of reading from a `File` bit-by-bit, so I can live without these changes. I'll push my changes to a branch so you can see what I was thinking, though.

**Comment by luser** [comment]
OK, I pushed my proposed change up, you can see it linked above. I looked at the expanded code from the macro, as well as the assembly generated for `cargo build --release` for [a simple example](https://github.com/luser/scroll-size-with/blob/master/src/main.rs) (n.b., the inline Pwrite impls are to work around #15), and here's what it looks like.

The `SizeWith` impls for `A` and `B` look like this (using `cargo-expand` to get the macro output):
```rust
impl ::scroll::ctx::SizeWith<::scroll::Endian> for A {
    type
    Units
    =
    usize;
    #[inline]
    fn size_with(ctx: &::scroll::Endian) -> Self::Units {
        0 + <u64>::size_with(ctx) + <u32>::size_with(ctx)
    }
}

impl ::scroll::ctx::SizeWith<::scroll::Endian> for B {
    type
    Units
    =
    usize;
    #[inline]
    fn size_with(ctx: &::scroll::Endian) -> Self::Units {
        0 + <A>::size_with(ctx)
    }
}
```

Those look like they get constant-folded away entirely by the compiler, the call to `B::size_with` turns into a constant load:

https://github.com/luser/scroll-size-with/blob/24d74861655971eaa153cfcac430418879d0a96f/src/main.rs#L54

```
   54     let size = B::size_with(&LE);
   000062b9:    48 c7 44 24 18 0c 00    mov qword ptr [rsp + 0x18], 0xc
   000062c0:    00 00
```

It's also useful to note that [the assertions](https://github.com/luser/scroll-size-with/blob/24d74861655971eaa153cfcac430418879d0a96f/src/main.rs#L59) in this example fail when built against `scroll_derive` without my patch, because `size_with` doesn't return the number of bytes that actually get written or read:
```
luser@eye7:/build/scroll-size-with$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/scroll-size-with`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `12`,
 right: `16`', src/main.rs:59:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
```

**Comment by luser** [comment]
I realized I could just add that example as a test, so I did so, but I had to trim it down to avoid #15.
